<?php
namespace ComunaAgris\Widgets;

use Elementor\Controls_Manager;
use Elementor\Group_Control_Image_Size;
use Elementor\Repeater;

if ( ! defined( 'ABSPATH' ) ) { exit; }

final class Home_Hero extends Base {
	public function get_name(): string { return 'agris-home-hero'; }
	public function get_title(): string { return __( '04 · Hero nyitóoldal', 'comuna-agris' ); }
	public function get_icon(): string { return 'eicon-slider-push'; }
	protected function register_controls(): void {
		$this->start_controls_section( 'content', array( 'label' => __( 'Tartalom', 'comuna-agris' ) ) );
		$this->add_control( 'eyebrow', array( 'label' => __( 'Állapot', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'Ghișeul este deschis · Luni–Vineri 8:00–16:00', 'label_block' => true ) );
		$this->add_control( 'title', array( 'label' => __( 'Főcím', 'comuna-agris' ), 'type' => Controls_Manager::TEXTAREA, 'default' => 'Servicii publice transparente pentru Comuna Agriș.' ) );
		$this->add_control( 'description', array( 'label' => __( 'Leírás', 'comuna-agris' ), 'type' => Controls_Manager::TEXTAREA, 'default' => 'Portal modern pentru documente, formulare, hotărâri, anunțuri oficiale și informații utile pentru cetățeni.' ) );
		$this->add_control( 'primary_text', array( 'label' => __( 'Elsődleges gomb', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'Vezi documentele' ) );
		$this->add_control( 'primary_link', array( 'label' => __( 'Elsődleges link', 'comuna-agris' ), 'type' => Controls_Manager::URL ) );
		$this->add_control( 'secondary_text', array( 'label' => __( 'Másodlagos gomb', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'Contact rapid' ) );
		$this->add_control( 'secondary_link', array( 'label' => __( 'Másodlagos link', 'comuna-agris' ), 'type' => Controls_Manager::URL ) );
		$this->add_control( 'background', array( 'label' => __( 'Háttérkép / kollázs', 'comuna-agris' ), 'type' => Controls_Manager::MEDIA ) );
		$this->add_group_control( Group_Control_Image_Size::get_type(), array( 'name' => 'background', 'default' => 'full' ) );
		$this->add_control( 'show_search', array( 'label' => __( 'Kereső megjelenítése', 'comuna-agris' ), 'type' => Controls_Manager::SWITCHER, 'default' => 'yes', 'return_value' => 'yes' ) );
		$this->end_controls_section();
		$this->start_controls_section( 'updates', array( 'label' => __( 'Kiemelt újdonságok', 'comuna-agris' ) ) );
		$this->add_control( 'updates_title', array( 'label' => __( 'Panel címe', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'Noutăți din portal' ) );
		$r = new Repeater();
		$r->add_control( 'day', array( 'label' => __( 'Nap / jel', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => '08' ) );
		$r->add_control( 'title', array( 'label' => __( 'Cím', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'Anunț important' ) );
		$r->add_control( 'meta', array( 'label' => __( 'Meta', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'Publicat recent' ) );
		$r->add_control( 'url', array( 'label' => __( 'Link', 'comuna-agris' ), 'type' => Controls_Manager::URL ) );
		$this->add_control( 'updates_items', array( 'type' => Controls_Manager::REPEATER, 'fields' => $r->get_controls(), 'title_field' => '{{{ day }}} · {{{ title }}}', 'default' => array( array( 'day' => '08', 'title' => 'ANUNȚ INDIVIDUAL', 'meta' => 'Publicat recent' ), array( 'day' => '18', 'title' => 'H.C.L. nr. 13–16 / 2026', 'meta' => 'Hotărâri publicate' ), array( 'day' => '24', 'title' => 'H.C.L. nr. 4–9 / 2026', 'meta' => 'Arhivă Consiliul Local' ) ) ) );
		$this->end_controls_section();
	}
	protected function render(): void {
		$s = $this->get_settings_for_display();
		$bg = ! empty( $s['background']['url'] ) ? ' style="--agris-hero-image:url(' . esc_url( $s['background']['url'] ) . ')"' : '';
		?><section class="agris-home-hero"<?php echo $bg; ?>><div class="agris-shell agris-hero-grid"><div><div class="agris-eyebrow"><i></i><?php echo esc_html( $s['eyebrow'] ); ?></div><h1><?php echo esc_html( $s['title'] ); ?></h1><p><?php echo esc_html( $s['description'] ); ?></p><div class="agris-actions"><a class="agris-button agris-button-primary" <?php echo self::link_attrs( $s['primary_link'] ); ?>><?php echo esc_html( $s['primary_text'] ); ?></a><a class="agris-button agris-button-light" <?php echo self::link_attrs( $s['secondary_link'] ); ?>><?php echo esc_html( $s['secondary_text'] ); ?></a></div><?php if ( 'yes' === $s['show_search'] ) : ?><form class="agris-hero-search" role="search" action="<?php echo esc_url( home_url( '/' ) ); ?>"><label class="screen-reader-text" for="agris-s-<?php echo esc_attr( $this->get_id() ); ?>"><?php esc_html_e( 'Caută', 'comuna-agris' ); ?></label><input id="agris-s-<?php echo esc_attr( $this->get_id() ); ?>" name="s" type="search" placeholder="<?php esc_attr_e( 'Căutați formulare, hotărâri, anunțuri…', 'comuna-agris' ); ?>"><button><?php esc_html_e( 'Caută', 'comuna-agris' ); ?></button></form><?php endif; ?></div><aside class="agris-hero-panel"><h2><?php echo esc_html( $s['updates_title'] ); ?></h2><?php foreach ( $s['updates_items'] as $item ) : ?><a class="agris-update" <?php echo self::link_attrs( $item['url'] ); ?>><b><?php echo esc_html( $item['day'] ); ?></b><span><strong><?php echo esc_html( $item['title'] ); ?></strong><small><?php echo esc_html( $item['meta'] ); ?></small></span></a><?php endforeach; ?></aside></div></section><?php
	}
}

final class Page_Hero extends Base {
	public function get_name(): string { return 'agris-page-hero'; }
	public function get_title(): string { return __( '05 · Hero belső oldal', 'comuna-agris' ); }
	public function get_icon(): string { return 'eicon-banner'; }
	protected function register_controls(): void {
		$this->start_controls_section( 'content', array( 'label' => __( 'Tartalom', 'comuna-agris' ) ) );
		$this->common_heading_controls( '', 'Titlul paginii' );
		$this->add_control( 'parent_label', array( 'label' => __( 'Morzsa szülő', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'Acasă' ) );
		$this->add_control( 'parent_link', array( 'label' => __( 'Morzsa link', 'comuna-agris' ), 'type' => Controls_Manager::URL, 'default' => array( 'url' => '/' ) ) );
		$this->add_control( 'current_label', array( 'label' => __( 'Aktuális oldal', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'Pagina curentă' ) );
		$this->add_control( 'background', array( 'label' => __( 'Háttérkép', 'comuna-agris' ), 'type' => Controls_Manager::MEDIA ) );
		$this->end_controls_section();
	}
	protected function render(): void { $s = $this->get_settings_for_display(); $bg = $s['background']['url'] ? ' style="--agris-page-image:url(' . esc_url( $s['background']['url'] ) . ')"' : ''; ?><section class="agris-page-hero"<?php echo $bg; ?>><div class="agris-shell"><div class="agris-breadcrumbs"><a <?php echo self::link_attrs( $s['parent_link'] ); ?>><?php echo esc_html( $s['parent_label'] ); ?></a><span>/</span><span><?php echo esc_html( $s['current_label'] ); ?></span></div><?php $this->render_heading( $s, 'h1' ); ?></div></section><?php }
}

final class Section_Heading extends Base {
	public function get_name(): string { return 'agris-section-heading'; }
	public function get_title(): string { return __( '06 · Szekció fejléc', 'comuna-agris' ); }
	public function get_icon(): string { return 'eicon-heading'; }
	protected function register_controls(): void { $this->start_controls_section( 'content', array( 'label' => __( 'Tartalom', 'comuna-agris' ) ) ); $this->common_heading_controls( 'Secțiune', 'Titlul secțiunii' ); $this->add_control( 'button_text', array( 'label' => __( 'Gomb szövege', 'comuna-agris' ), 'type' => Controls_Manager::TEXT ) ); $this->add_control( 'button_link', array( 'label' => __( 'Gomb linkje', 'comuna-agris' ), 'type' => Controls_Manager::URL ) ); $this->end_controls_section(); }
	protected function render(): void { $s = $this->get_settings_for_display(); ?><div class="agris-section-heading"><div><?php $this->render_heading( $s ); ?></div><?php if ( $s['button_text'] ) : ?><a class="agris-button agris-button-outline" <?php echo self::link_attrs( $s['button_link'] ); ?>><?php echo esc_html( $s['button_text'] ); ?></a><?php endif; ?></div><?php }
}

final class Services_Grid extends Base {
	public function get_name(): string { return 'agris-services-grid'; }
	public function get_title(): string { return __( '07 · Szolgáltatások rács', 'comuna-agris' ); }
	public function get_icon(): string { return 'eicon-gallery-grid'; }
	protected function register_controls(): void { $this->start_controls_section( 'items', array( 'label' => __( 'Szolgáltatások', 'comuna-agris' ) ) ); $r = new Repeater(); $r->add_control( 'icon', array( 'label' => __( 'Rövid jel', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'TAX' ) ); $r->add_control( 'title', array( 'label' => __( 'Cím', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'Taxe și impozite' ) ); $r->add_control( 'description', array( 'label' => __( 'Leírás', 'comuna-agris' ), 'type' => Controls_Manager::TEXTAREA, 'default' => 'Informații și servicii pentru cetățeni.' ) ); $r->add_control( 'url', array( 'label' => __( 'Link', 'comuna-agris' ), 'type' => Controls_Manager::URL ) ); $this->add_control( 'items_list', array( 'type' => Controls_Manager::REPEATER, 'fields' => $r->get_controls(), 'title_field' => '{{{ icon }}} · {{{ title }}}', 'default' => array( array( 'icon' => 'TAX', 'title' => 'Taxe și impozite' ), array( 'icon' => 'PDF', 'title' => 'Formulare tipizate' ), array( 'icon' => 'URB', 'title' => 'Urbanism' ), array( 'icon' => 'AGR', 'title' => 'Registru agricol' ) ) ) ); $this->add_control( 'columns', array( 'label' => __( 'Oszlopok', 'comuna-agris' ), 'type' => Controls_Manager::SELECT, 'options' => array( '2' => '2', '3' => '3', '4' => '4' ), 'default' => '4' ) ); $this->end_controls_section(); }
	protected function render(): void { $s = $this->get_settings_for_display(); ?><div class="agris-grid agris-grid-<?php echo esc_attr( $s['columns'] ); ?>"><?php foreach ( $s['items_list'] as $item ) : ?><a class="agris-service-card" <?php echo self::link_attrs( $item['url'] ); ?>><span class="agris-icon-box"><?php echo esc_html( $item['icon'] ); ?></span><h3><?php echo esc_html( $item['title'] ); ?></h3><p><?php echo esc_html( $item['description'] ); ?></p><i aria-hidden="true">→</i></a><?php endforeach; ?></div><?php }
}

final class Content_Media extends Base {
	public function get_name(): string { return 'agris-content-media'; }
	public function get_title(): string { return __( '08 · Tartalom + kép', 'comuna-agris' ); }
	public function get_icon(): string { return 'eicon-image-box'; }
	protected function register_controls(): void { $this->start_controls_section( 'content', array( 'label' => __( 'Tartalom', 'comuna-agris' ) ) ); $this->common_heading_controls( 'Comuna', 'Istorie, cultură și natură' ); $this->add_control( 'content', array( 'label' => __( 'Szöveg', 'comuna-agris' ), 'type' => Controls_Manager::WYSIWYG, 'default' => '<p>Adăugați aici conținutul paginii.</p>' ) ); $this->add_control( 'image', array( 'label' => __( 'Kép', 'comuna-agris' ), 'type' => Controls_Manager::MEDIA ) ); $this->add_group_control( Group_Control_Image_Size::get_type(), array( 'name' => 'image', 'default' => 'large' ) ); $this->add_control( 'image_side', array( 'label' => __( 'Kép helye', 'comuna-agris' ), 'type' => Controls_Manager::SELECT, 'options' => array( 'right' => 'Jobbra', 'left' => 'Balra' ), 'default' => 'right' ) ); $this->end_controls_section(); }
	protected function render(): void { $s = $this->get_settings_for_display(); $has_image = ! empty( $s['image']['id'] ) || ! empty( $s['image']['url'] ); ?><div class="agris-content-media is-<?php echo esc_attr( $s['image_side'] ); ?> <?php echo $has_image ? 'has-media' : 'has-no-media'; ?>"><div><?php $this->render_heading( $s ); ?><div class="agris-richtext"><?php echo wp_kses_post( $s['content'] ); ?></div></div><?php if ( $has_image ) : ?><div class="agris-media-frame"><?php echo Group_Control_Image_Size::get_attachment_image_html( $s, 'image', 'image' ); ?></div><?php endif; ?></div><?php }
}

final class Person_Profile extends Base {
	public function get_name(): string { return 'agris-person-profile'; }
	public function get_title(): string { return __( '09 · Vezetői profil', 'comuna-agris' ); }
	public function get_icon(): string { return 'eicon-person'; }
	protected function register_controls(): void { $this->start_controls_section( 'profile', array( 'label' => __( 'Személy', 'comuna-agris' ) ) ); $this->add_control( 'photo', array( 'label' => __( 'Fotó', 'comuna-agris' ), 'type' => Controls_Manager::MEDIA ) ); $this->add_group_control( Group_Control_Image_Size::get_type(), array( 'name' => 'photo', 'default' => 'large' ) ); $this->add_control( 'role', array( 'label' => __( 'Tisztség', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'Primar' ) ); $this->add_control( 'name', array( 'label' => __( 'Név', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'Szabó Elek' ) ); $this->add_control( 'subtitle', array( 'label' => __( 'Alcím', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'Primarul Comunei Agriș' ) ); $this->add_control( 'bio', array( 'label' => __( 'Bemutatkozás', 'comuna-agris' ), 'type' => Controls_Manager::WYSIWYG ) ); $this->add_control( 'phone', array( 'label' => __( 'Telefon', 'comuna-agris' ), 'type' => Controls_Manager::TEXT ) ); $this->add_control( 'email', array( 'label' => __( 'Email', 'comuna-agris' ), 'type' => Controls_Manager::TEXT ) ); $this->add_control( 'office', array( 'label' => __( 'Fogadóóra / információ', 'comuna-agris' ), 'type' => Controls_Manager::TEXT ) ); $this->end_controls_section(); }
	protected function render(): void { $s = $this->get_settings_for_display(); ?><article class="agris-person"><div class="agris-person-photo"><?php if ( $s['photo']['url'] ) { echo Group_Control_Image_Size::get_attachment_image_html( $s, 'photo', 'photo' ); } else { echo '<span>◎</span>'; } ?></div><div class="agris-person-body"><span class="agris-tag"><?php echo esc_html( $s['role'] ); ?></span><h2><?php echo esc_html( $s['name'] ); ?></h2><p class="agris-muted"><?php echo esc_html( $s['subtitle'] ); ?></p><?php echo wp_kses_post( $s['bio'] ); ?><div class="agris-detail-list"><?php if ( $s['phone'] ) : ?><a href="tel:<?php echo esc_attr( preg_replace( '/\D+/', '', $s['phone'] ) ); ?>"><b>TEL</b><span><?php echo esc_html( $s['phone'] ); ?></span></a><?php endif; ?><?php if ( $s['email'] ) : ?><a href="mailto:<?php echo esc_attr( antispambot( $s['email'] ) ); ?>"><b>@</b><span><?php echo esc_html( antispambot( $s['email'] ) ); ?></span></a><?php endif; ?><?php if ( $s['office'] ) : ?><div><b>ORĂ</b><span><?php echo esc_html( $s['office'] ); ?></span></div><?php endif; ?></div></div></article><?php }
}

final class Schedule_Grid extends Base {
	public function get_name(): string { return 'agris-schedule-grid'; }
	public function get_title(): string { return __( '10 · Fogadóórák', 'comuna-agris' ); }
	public function get_icon(): string { return 'eicon-calendar'; }
	protected function register_controls(): void { $this->start_controls_section( 'content', array( 'label' => __( 'Program', 'comuna-agris' ) ) ); $this->common_heading_controls( 'Program audiențe', 'Acces la conducere' ); $r = new Repeater(); $r->add_control( 'icon', array( 'label' => __( 'Jel', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'PR' ) ); $r->add_control( 'title', array( 'label' => __( 'Tisztség', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'Primar' ) ); $r->add_control( 'time', array( 'label' => __( 'Időpont', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'Luni, 10:00–12:00' ) ); $this->add_control( 'items_list', array( 'type' => Controls_Manager::REPEATER, 'fields' => $r->get_controls(), 'title_field' => '{{{ title }}} · {{{ time }}}', 'default' => array( array( 'icon' => 'PR', 'title' => 'Primar', 'time' => 'Luni, 10:00–12:00' ), array( 'icon' => 'VP', 'title' => 'Viceprimar', 'time' => 'Miercuri, 10:00–12:00' ) ) ) ); $this->end_controls_section(); }
	protected function render(): void { $s = $this->get_settings_for_display(); ?><section class="agris-info-panel"><?php $this->render_heading( $s ); ?><div class="agris-grid agris-grid-2"><?php foreach ( $s['items_list'] as $item ) : ?><div class="agris-detail"><b><?php echo esc_html( $item['icon'] ); ?></b><span><strong><?php echo esc_html( $item['title'] ); ?></strong><small><?php echo esc_html( $item['time'] ); ?></small></span></div><?php endforeach; ?></div></section><?php }
}

final class Council_Members extends Base {
	public function get_name(): string { return 'agris-council-members'; }
	public function get_title(): string { return __( '11 · Helyi tanács', 'comuna-agris' ); }
	public function get_icon(): string { return 'eicon-users'; }
	protected function register_controls(): void { $this->start_controls_section( 'members', array( 'label' => __( 'Tagok', 'comuna-agris' ) ) ); $r = new Repeater(); $r->add_control( 'name', array( 'label' => __( 'Név', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'Nume consilier' ) ); $r->add_control( 'party', array( 'label' => __( 'Párt / csoport', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'Independent' ) ); $r->add_control( 'role', array( 'label' => __( 'Szerepkör', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'Consilier local' ) ); $r->add_control( 'email', array( 'label' => __( 'Email', 'comuna-agris' ), 'type' => Controls_Manager::TEXT ) ); $this->add_control( 'items_list', array( 'type' => Controls_Manager::REPEATER, 'fields' => $r->get_controls(), 'title_field' => '{{{ name }}} · {{{ party }}}', 'default' => array( array( 'name' => 'Nume consilier', 'party' => 'UDMR' ), array( 'name' => 'Nume consilier', 'party' => 'PNL' ), array( 'name' => 'Nume consilier', 'party' => 'PSD' ) ) ) ); $this->add_control( 'columns', array( 'label' => __( 'Oszlopok', 'comuna-agris' ), 'type' => Controls_Manager::SELECT, 'options' => array( '2' => '2', '3' => '3', '4' => '4' ), 'default' => '3' ) ); $this->end_controls_section(); }
	protected function render(): void { $s = $this->get_settings_for_display(); ?><div class="agris-grid agris-grid-<?php echo esc_attr( $s['columns'] ); ?>"><?php foreach ( $s['items_list'] as $item ) : ?><article class="agris-council-card"><span><?php echo esc_html( $item['party'] ); ?></span><h3><?php echo esc_html( $item['name'] ); ?></h3><p><?php echo esc_html( $item['role'] ); ?></p><?php if ( $item['email'] ) : ?><a href="mailto:<?php echo esc_attr( antispambot( $item['email'] ) ); ?>"><?php echo esc_html( antispambot( $item['email'] ) ); ?></a><?php endif; ?></article><?php endforeach; ?></div><?php }
}

final class Link_List extends Base {
	public function get_name(): string { return 'agris-link-list'; }
	public function get_title(): string { return __( '12 · Linklista / oldalsáv', 'comuna-agris' ); }
	public function get_icon(): string { return 'eicon-editor-list-ul'; }
	protected function register_controls(): void { $this->start_controls_section( 'links', array( 'label' => __( 'Linkek', 'comuna-agris' ) ) ); $this->add_control( 'title', array( 'label' => __( 'Cím', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'Linkuri utile' ) ); $r = new Repeater(); $r->add_control( 'icon', array( 'label' => __( 'Jel', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'DOC' ) ); $r->add_control( 'label', array( 'label' => __( 'Cím', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'Document util' ) ); $r->add_control( 'meta', array( 'label' => __( 'Alcím', 'comuna-agris' ), 'type' => Controls_Manager::TEXT ) ); $r->add_control( 'url', array( 'label' => __( 'Link', 'comuna-agris' ), 'type' => Controls_Manager::URL ) ); $this->add_control( 'items_list', array( 'type' => Controls_Manager::REPEATER, 'fields' => $r->get_controls(), 'title_field' => '{{{ icon }}} · {{{ label }}}' ) ); $this->end_controls_section(); }
	protected function render(): void { $s = $this->get_settings_for_display(); ?><div class="agris-link-widget"><?php if ( $s['title'] ) : ?><h2><?php echo esc_html( $s['title'] ); ?></h2><?php endif; ?><?php foreach ( $s['items_list'] as $item ) : ?><a class="agris-doc-card" <?php echo self::link_attrs( $item['url'] ); ?>><b><?php echo esc_html( $item['icon'] ); ?></b><span><strong><?php echo esc_html( $item['label'] ); ?></strong><small><?php echo esc_html( $item['meta'] ); ?></small></span></a><?php endforeach; ?></div><?php }
}

final class Contact_Details extends Base {
	public function get_name(): string { return 'agris-contact-details'; }
	public function get_title(): string { return __( '13 · Kapcsolati adatok', 'comuna-agris' ); }
	public function get_icon(): string { return 'eicon-map-pin'; }
	protected function register_controls(): void { $this->start_controls_section( 'content', array( 'label' => __( 'Kapcsolat', 'comuna-agris' ) ) ); $this->common_heading_controls( 'Contact', 'Primăria Comunei Agriș' ); $this->add_control( 'address', array( 'label' => __( 'Cím', 'comuna-agris' ), 'type' => Controls_Manager::TEXTAREA, 'default' => 'Agriș, str. Csury Balint, nr. 68, Satu Mare' ) ); $this->add_control( 'phone', array( 'label' => __( 'Telefon', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => '0261 878 112' ) ); $this->add_control( 'email', array( 'label' => __( 'Email', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'primaria@comunaagris.ro' ) ); $this->add_control( 'hours', array( 'label' => __( 'Nyitvatartás', 'comuna-agris' ), 'type' => Controls_Manager::TEXTAREA, 'default' => 'Luni–Vineri: 8:00–16:00' ) ); $this->add_control( 'map_embed', array( 'label' => __( 'Google Maps beágyazási URL', 'comuna-agris' ), 'type' => Controls_Manager::URL, 'description' => __( 'A Google Maps „Térkép beágyazása” iframe src értéke.', 'comuna-agris' ) ) ); $this->end_controls_section(); }
	protected function render(): void { $s = $this->get_settings_for_display(); ?><div class="agris-contact-layout"><div class="agris-contact-card"><?php $this->render_heading( $s ); ?><div class="agris-detail-list"><div><b>LOC</b><span><?php echo nl2br( esc_html( $s['address'] ) ); ?></span></div><a href="tel:<?php echo esc_attr( preg_replace( '/\D+/', '', $s['phone'] ) ); ?>"><b>TEL</b><span><?php echo esc_html( $s['phone'] ); ?></span></a><a href="mailto:<?php echo esc_attr( antispambot( $s['email'] ) ); ?>"><b>@</b><span><?php echo esc_html( antispambot( $s['email'] ) ); ?></span></a><div><b>ORĂ</b><span><?php echo nl2br( esc_html( $s['hours'] ) ); ?></span></div></div></div><?php if ( $s['map_embed']['url'] ) : ?><iframe class="agris-map" loading="lazy" referrerpolicy="no-referrer-when-downgrade" src="<?php echo esc_url( $s['map_embed']['url'] ); ?>" title="<?php esc_attr_e( 'Hartă', 'comuna-agris' ); ?>"></iframe><?php endif; ?></div><?php }
}

final class Contact_Form extends Base {
	public function get_name(): string { return 'agris-contact-form'; }
	public function get_title(): string { return __( '14 · Kapcsolati űrlap', 'comuna-agris' ); }
	public function get_icon(): string { return 'eicon-form-horizontal'; }
	protected function register_controls(): void { $this->start_controls_section( 'content', array( 'label' => __( 'Űrlap', 'comuna-agris' ) ) ); $this->common_heading_controls( 'Mesaj', 'Trimiteți-ne un mesaj' ); $this->add_control( 'recipient', array( 'label' => __( 'Címzett email', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => get_option( 'admin_email' ) ) ); $this->add_control( 'button_text', array( 'label' => __( 'Gomb', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'Trimite mesajul' ) ); $this->add_control( 'privacy_text', array( 'label' => __( 'Adatvédelmi szöveg', 'comuna-agris' ), 'type' => Controls_Manager::TEXTAREA, 'default' => 'Datele sunt folosite exclusiv pentru a răspunde solicitării.' ) ); $this->end_controls_section(); }
	protected function render(): void { $s = $this->get_settings_for_display(); $recipient = sanitize_email( $s['recipient'] ) ?: get_option( 'admin_email' ); ?><section class="agris-form-card"><?php $this->render_heading( $s ); ?><form class="agris-contact-form" novalidate><input type="hidden" name="recipient" value="<?php echo esc_attr( $recipient ); ?>"><input type="hidden" name="recipient_hash" value="<?php echo esc_attr( wp_hash( $recipient . '|agris_contact' ) ); ?>"><div class="agris-form-two"><label><?php esc_html_e( 'Nume și prenume', 'comuna-agris' ); ?> *<input name="name" required autocomplete="name"></label><label><?php esc_html_e( 'Email', 'comuna-agris' ); ?> *<input name="email" type="email" required autocomplete="email"></label></div><label><?php esc_html_e( 'Subiect', 'comuna-agris' ); ?> *<input name="subject" required></label><label><?php esc_html_e( 'Mesaj', 'comuna-agris' ); ?> *<textarea name="message" rows="6" required></textarea></label><label class="agris-honeypot" aria-hidden="true">Website<input name="website" tabindex="-1" autocomplete="off"></label><p class="agris-form-privacy"><?php echo esc_html( $s['privacy_text'] ); ?></p><button class="agris-button agris-button-primary" type="submit"><?php echo esc_html( $s['button_text'] ); ?></button><div class="agris-form-status" role="status" aria-live="polite"></div></form></section><?php }
}

final class Cta_Banner extends Base {
	public function get_name(): string { return 'agris-cta-banner'; }
	public function get_title(): string { return __( '15 · CTA / intézményi banner', 'comuna-agris' ); }
	public function get_icon(): string { return 'eicon-call-to-action'; }
	protected function register_controls(): void { $this->start_controls_section( 'content', array( 'label' => __( 'Banner', 'comuna-agris' ) ) ); $this->common_heading_controls( 'Transparență administrativă', 'Guvernare transparentă, deschisă și participativă' ); $this->add_control( 'image', array( 'label' => __( 'Logó / bannerkép', 'comuna-agris' ), 'type' => Controls_Manager::MEDIA ) ); $this->add_group_control( Group_Control_Image_Size::get_type(), array( 'name' => 'image', 'default' => 'large' ) ); $this->add_control( 'button_text', array( 'label' => __( 'Gomb', 'comuna-agris' ), 'type' => Controls_Manager::TEXT ) ); $this->add_control( 'button_link', array( 'label' => __( 'Link', 'comuna-agris' ), 'type' => Controls_Manager::URL ) ); $this->end_controls_section(); }
	protected function render(): void { $s = $this->get_settings_for_display(); ?><section class="agris-cta"><div><?php $this->render_heading( $s ); ?><?php if ( $s['button_text'] ) : ?><a class="agris-button agris-button-light" <?php echo self::link_attrs( $s['button_link'] ); ?>><?php echo esc_html( $s['button_text'] ); ?></a><?php endif; ?></div><?php if ( $s['image']['url'] ) : ?><div class="agris-cta-image"><?php echo Group_Control_Image_Size::get_attachment_image_html( $s, 'image', 'image' ); ?></div><?php endif; ?></section><?php }
}

final class Photo_Gallery extends Base {
	public function get_name(): string { return 'agris-photo-gallery'; }
	public function get_title(): string { return __( '16 · Fotógaléria', 'comuna-agris' ); }
	public function get_icon(): string { return 'eicon-gallery-grid'; }
	protected function register_controls(): void { $this->start_controls_section( 'gallery', array( 'label' => __( 'Képek', 'comuna-agris' ) ) ); $this->common_heading_controls( 'Galerie', 'Comuna în imagini' ); $r = new Repeater(); $r->add_control( 'image', array( 'label' => __( 'Kép', 'comuna-agris' ), 'type' => Controls_Manager::MEDIA ) ); $r->add_control( 'caption', array( 'label' => __( 'Képaláírás', 'comuna-agris' ), 'type' => Controls_Manager::TEXT ) ); $this->add_control( 'items_list', array( 'type' => Controls_Manager::REPEATER, 'fields' => $r->get_controls(), 'title_field' => '{{{ caption }}}' ) ); $this->add_control( 'columns', array( 'label' => __( 'Oszlopok', 'comuna-agris' ), 'type' => Controls_Manager::SELECT, 'options' => array( '2' => '2', '3' => '3', '4' => '4' ), 'default' => '3' ) ); $this->end_controls_section(); }
	protected function render(): void { $s = $this->get_settings_for_display(); ?><section class="agris-gallery-widget"><?php $this->render_heading( $s ); ?><div class="agris-gallery agris-grid-<?php echo esc_attr( $s['columns'] ); ?>"><?php foreach ( $s['items_list'] as $item ) : if ( empty( $item['image']['url'] ) ) continue; ?><a href="<?php echo esc_url( $item['image']['url'] ); ?>" data-elementor-open-lightbox="yes" data-elementor-lightbox-slideshow="agris-<?php echo esc_attr( $this->get_id() ); ?>"><img src="<?php echo esc_url( $item['image']['url'] ); ?>" alt="<?php echo esc_attr( $item['caption'] ); ?>" loading="lazy"><?php if ( $item['caption'] ) : ?><span><?php echo esc_html( $item['caption'] ); ?></span><?php endif; ?></a><?php endforeach; ?></div></section><?php }
}

final class Data_Table extends Base {
	public function get_name(): string { return 'agris-data-table'; }
	public function get_title(): string { return __( '17 · Adattábla / nyilvántartás', 'comuna-agris' ); }
	public function get_icon(): string { return 'eicon-table'; }
	protected function register_controls(): void { $this->start_controls_section( 'table', array( 'label' => __( 'Táblázat', 'comuna-agris' ) ) ); $this->add_control( 'caption', array( 'label' => __( 'Akadálymentes táblázatcím', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'Registru public' ) ); foreach ( array( 1, 2, 3, 4 ) as $i ) { $this->add_control( 'heading_' . $i, array( 'label' => sprintf( __( '%d. oszlop fejléce', 'comuna-agris' ), $i ), 'type' => Controls_Manager::TEXT, 'default' => 1 === $i ? 'Denumire' : '' ) ); } $r = new Repeater(); foreach ( array( 1, 2, 3, 4 ) as $i ) { $r->add_control( 'cell_' . $i, array( 'label' => sprintf( __( '%d. oszlop', 'comuna-agris' ), $i ), 'type' => Controls_Manager::TEXT, 'label_block' => true ) ); } $r->add_control( 'url', array( 'label' => __( 'Sor linkje (opcionális)', 'comuna-agris' ), 'type' => Controls_Manager::URL ) ); $this->add_control( 'rows', array( 'type' => Controls_Manager::REPEATER, 'fields' => $r->get_controls(), 'title_field' => '{{{ cell_1 }}}', 'default' => array( array( 'cell_1' => 'Înregistrare publică', 'cell_2' => '2026', 'cell_3' => 'Publicat' ) ) ) ); $this->end_controls_section(); }
	protected function render(): void { $s = $this->get_settings_for_display(); $headings = array_filter( array( $s['heading_1'], $s['heading_2'], $s['heading_3'], $s['heading_4'] ), static fn( $v ) => '' !== $v ); $count = count( $headings ); ?><div class="agris-table-wrap"><table class="agris-table"><caption><?php echo esc_html( $s['caption'] ); ?></caption><thead><tr><?php foreach ( $headings as $heading ) : ?><th scope="col"><?php echo esc_html( $heading ); ?></th><?php endforeach; ?></tr></thead><tbody><?php foreach ( $s['rows'] as $row ) : ?><tr><?php for ( $i = 1; $i <= $count; $i++ ) : ?><td><?php if ( 1 === $i && ! empty( $row['url']['url'] ) ) : ?><a <?php echo self::link_attrs( $row['url'] ); ?>><?php echo esc_html( $row[ 'cell_' . $i ] ); ?></a><?php else : echo esc_html( $row[ 'cell_' . $i ] ); endif; ?></td><?php endfor; ?></tr><?php endforeach; ?></tbody></table></div><?php }
}

final class Stats_Bars extends Base {
	public function get_name(): string { return 'agris-stats-bars'; }
	public function get_title(): string { return __( '18 · Statisztika / megoszlás', 'comuna-agris' ); }
	public function get_icon(): string { return 'eicon-skill-bar'; }
	protected function register_controls(): void { $this->start_controls_section( 'stats', array( 'label' => __( 'Adatok', 'comuna-agris' ) ) ); $this->common_heading_controls( 'Componență', 'Distribuția consiliului' ); $r = new Repeater(); $r->add_control( 'label', array( 'label' => __( 'Megnevezés', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'Grup' ) ); $r->add_control( 'value', array( 'label' => __( 'Érték', 'comuna-agris' ), 'type' => Controls_Manager::NUMBER, 'default' => 50, 'min' => 0, 'max' => 100 ) ); $r->add_control( 'suffix', array( 'label' => __( 'Utótag', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => '%' ) ); $r->add_control( 'color', array( 'label' => __( 'Szín', 'comuna-agris' ), 'type' => Controls_Manager::COLOR, 'default' => '#1b5e20' ) ); $this->add_control( 'items_list', array( 'type' => Controls_Manager::REPEATER, 'fields' => $r->get_controls(), 'title_field' => '{{{ label }}} · {{{ value }}}{{{ suffix }}}', 'default' => array( array( 'label' => 'UDMR', 'value' => 55, 'color' => '#1b5e20' ), array( 'label' => 'PNL', 'value' => 27, 'color' => '#1d4ed8' ), array( 'label' => 'PSD', 'value' => 18, 'color' => '#b42318' ) ) ) ); $this->end_controls_section(); }
	protected function render(): void { $s = $this->get_settings_for_display(); ?><section class="agris-stats"><?php $this->render_heading( $s ); ?><div class="agris-stats-list"><?php foreach ( $s['items_list'] as $item ) : $value = max( 0, min( 100, (float) $item['value'] ) ); ?><div class="agris-stat"><div><strong><?php echo esc_html( $item['label'] ); ?></strong><span><?php echo esc_html( $item['value'] . $item['suffix'] ); ?></span></div><i><b style="width:<?php echo esc_attr( $value ); ?>%;background:<?php echo esc_attr( $item['color'] ); ?>"></b></i></div><?php endforeach; ?></div></section><?php }
}
