<?php
namespace ComunaAgris\Widgets;

use Elementor\Controls_Manager;

if ( ! defined( 'ABSPATH' ) ) { exit; }

final class Contact_Form extends Base {
	public function get_name(): string { return 'agris-contact-form'; }
	public function get_title(): string { return __( '14 · Kapcsolati űrlap', 'comuna-agris' ); }
	public function get_icon(): string { return 'eicon-form-horizontal'; }
	protected function register_controls(): void { $this->start_controls_section( 'content', array( 'label' => __( 'Űrlap', 'comuna-agris' ) ) ); $this->common_heading_controls( 'Mesaj', 'Trimiteți-ne un mesaj' ); $this->add_control( 'recipient', array( 'label' => __( 'Címzett email', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => get_option( 'admin_email' ) ) ); $this->add_control( 'language', array( 'label' => __( 'Nyelv', 'comuna-agris' ), 'type' => Controls_Manager::SELECT, 'default' => 'ro', 'options' => array( 'ro' => 'Română', 'hu' => 'Magyar' ) ) ); $this->add_control( 'name_label', array( 'label' => __( 'Név mező', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'Nume și prenume' ) ); $this->add_control( 'email_label', array( 'label' => __( 'Email mező', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'Email' ) ); $this->add_control( 'subject_label', array( 'label' => __( 'Tárgy mező', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'Subiect' ) ); $this->add_control( 'message_label', array( 'label' => __( 'Üzenet mező', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'Mesaj' ) ); $this->add_control( 'button_text', array( 'label' => __( 'Gomb', 'comuna-agris' ), 'type' => Controls_Manager::TEXT, 'default' => 'Trimite mesajul' ) ); $this->add_control( 'privacy_text', array( 'label' => __( 'Adatvédelmi szöveg', 'comuna-agris' ), 'type' => Controls_Manager::TEXTAREA, 'default' => 'Datele sunt folosite exclusiv pentru a răspunde solicitării.' ) ); $this->end_controls_section();
		$this->register_common_style_controls();
	}
	protected function render(): void { $s = $this->get_settings_for_display(); $recipient = sanitize_email( $s['recipient'] ) ?: get_option( 'admin_email' ); ?><section class="agris-form-card"><?php $this->render_heading( $s ); ?><form class="agris-contact-form" novalidate><input type="hidden" name="recipient" value="<?php echo esc_attr( $recipient ); ?>"><input type="hidden" name="recipient_hash" value="<?php echo esc_attr( wp_hash( $recipient . '|agris_contact' ) ); ?>"><input type="hidden" name="language" value="<?php echo esc_attr( 'hu' === $s['language'] ? 'hu' : 'ro' ); ?>"><div class="agris-form-two"><label><?php echo esc_html( $s['name_label'] ); ?> *<input name="name" required autocomplete="name"></label><label><?php echo esc_html( $s['email_label'] ); ?> *<input name="email" type="email" required autocomplete="email"></label></div><label><?php echo esc_html( $s['subject_label'] ); ?> *<input name="subject" required></label><label><?php echo esc_html( $s['message_label'] ); ?> *<textarea name="message" rows="6" required></textarea></label><label class="agris-honeypot" aria-hidden="true">Website<input name="website" tabindex="-1" autocomplete="off"></label><p class="agris-form-privacy"><?php echo esc_html( $s['privacy_text'] ); ?></p><button class="agris-button agris-button-primary" type="submit"><?php echo esc_html( $s['button_text'] ); ?></button><div class="agris-form-status" role="status" aria-live="polite"></div></form></section><?php }
}
